//
// Created by ozzadar on 2021-08-12.
//

#pragma once
#include <string>

namespace OZZ {
    enum class InputKey {
        Unknown,

        KeyA,
        KeyB,
        KeyC,
        KeyD,
        KeyE,
        KeyF,
        KeyG,
        KeyH,
        KeyI,
        KeyJ,
        KeyK,
        KeyL,
        KeyM,
        KeyN,
        KeyO,
        KeyP,
        KeyQ,
        KeyR,
        KeyS,
        KeyT,
        KeyU,
        KeyV,
        KeyW,
        KeyX,
        KeyY,
        KeyZ,
        KeyBracketL,
        KeyBracketR,
        KeyBackslash,
        KeySemicolon,
        KeyApostrophe,
        KeyComma,
        KeyPeriod,
        KeyForwardSlash,
        KeyTilde,
        KeyEscape,
        KeyF1,
        KeyF2,
        KeyF3,
        KeyF4,
        KeyF5,
        KeyF6,
        KeyF7,
        KeyF8,
        KeyF9,
        KeyF10,
        KeyF11,
        KeyF12,
        KeyPrintScreen,
        KeyScrollLock,
        KeyPauseBreak,
        KeyInsert,
        KeyHome,
        KeyPageUp,
        KeyPageDown,
        KeyEnd,
        KeyDelete,
        KeyBackspace,
        KeyArrowUp,
        KeyArrowLeft,
        KeyArrowRight,
        KeyArrowDown,
        KeyTab,
        KeyCapsLock,
        KeyShiftLeft,
        KeyShiftRight,
        KeyEnter,
        KeyCtrlLeft,
        KeyCtrlRight,
        KeyAltLeft,
        KeyAltRight,
        KeyNumlock,
        KeyNumpadDivide,
        KeyNumpadMultiply,
        KeyNumpadMinus,
        KeyNumpadPlus,
        KeyNumpadReturn,
        KeyNumpadPeriod,
        KeyNumpad1,
        KeyNumpad2,
        KeyNumpad3,
        KeyNumpad4,
        KeyNumpad5,
        KeyNumpad6,
        KeyNumpad7,
        KeyNumpad8,
        KeyNumpad9,
        KeyNumpad0,
        KeyMax,

        ControllerButtonA,
        ControllerButtonB,
        ControllerButtonX,
        ControllerButtonY,
        ControllerButtonSelect,
        ControllerButtonGuide,
        ControllerButtonStart,
        ControllerButtonLeftStick,
        ControllerButtonRightStick,
        ControllerButtonLeftShoulder,
        ControllerButtonRightShoulder,
        ControllerButtonDpadUp,
        ControllerButtonDpadDown,
        ControllerButtonDpadLeft,
        ControllerButtonDpadRight,
        ControllerButtonMisc1,
        ControllerButtonPaddle1,
        ControllerButtonPaddle2,
        ControllerButtonPaddle3,
        ControllerButtonPaddle4,
        ControllerButtonTouchPad,
        ControllerAxisLeftX,
        ControllerAxisLeftY,
        ControllerAxisRightX,
        ControllerAxisRightY,
        ControllerAxisTriggerLeft,
        ControllerAxisTriggerRight,
        ControllerMax,

        MouseX,
        MouseY,
        MouseMoveX,
        MouseMoveY,
        MouseButtonRight,
        MouseButtonLeft,
        MouseButtonMiddle,
        MouseMax
    };

    enum class InputSource {
        Unknown,
        Keyboard,
        Controller,
        Mouse,
    };

    struct InputAction {
        std::string ActionName;
        float Scale { 1.f };
    };

    InputSource GetInputSourceFromKey(InputKey key);
}